@extends('layouts.master', ['activePage' => 'payments', 'titlePage' => 'Payment Receipt'])

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="py-3 mb-4">
        <span class="text-muted fw-light">Gym Management / Payments /</span> Receipt
    </h4>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="mb-0">Payment Receipt #{{ $payment->receipt_number ?? $payment->id }}</h5>
            <div>
                <button onclick="window.print()" class="btn btn-primary">
                    <i class="bx bx-printer me-1"></i> Print Receipt
                </button>
                <a href="{{ route('payments.index') }}" class="btn btn-outline-secondary">
                    <i class="bx bx-arrow-back me-1"></i> Back to Payments
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h6 class="text-muted">Gym Information</h6>
                    <p><strong>Your Gym Name</strong></p>
                    <p>123 Fitness Street, City, Country</p>
                    <p>Email: info@yourgym.com</p>
                    <p>Phone: (123) 456-7890</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <h6 class="text-muted">Receipt Details</h6>
                    <p><strong>Receipt Number:</strong> {{ $payment->receipt_number ?? 'N/A' }}</p>
                    <p><strong>Payment Date:</strong> {{ $payment->payment_date->format('Y-m-d H:i A') }}</p>
                    <p><strong>Transaction ID:</strong> {{ $payment->transaction_id ?? 'N/A' }}</p>
                </div>
            </div>
            <hr>
            <div class="row mb-4">
                <div class="col-md-6">
                    <h6 class="text-muted">Member Information</h6>
                    <p><strong>Name:</strong> {{ $payment->member?->full_name ?? 'N/A' }}</p>
                    <p><strong>Email:</strong> {{ $payment->member?->email ?? 'N/A' }}</p>
                    <p><strong>Phone:</strong> {{ $payment->member?->phone ?? 'N/A' }}</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <h6 class="text-muted">Payment Information</h6>
                    <p><strong>Membership Type:</strong> {{ $payment->membershipType?->type_name ?? 'N/A' }}</p>
                    <p><strong>Class:</strong> {{ $payment->class?->class_name ?? 'N/A' }}</p>
                    <p><strong>Class Registration:</strong> {{ $payment->classRegistration?->id ?? 'N/A' }}</p>
                    <p><strong>Payment Method:</strong> {{ $payment->paymentMethod?->display_name ?? 'N/A' }}</p>
                    <p><strong>Status:</strong> {!! $payment->status_badge !!}</p>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-12">
                    <h6 class="text-muted">Payment Details</h6>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Description</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ $payment->description ?? ($payment->membershipType?->type_name ?? $payment->class?->class_name ?? 'Payment') }}</td>
                                    <td>{{ '$' . number_format($payment->amount, 2) }}</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Total</th>
                                    <th>{{ '$' . number_format($payment->amount, 2) }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h6 class="text-muted">Notes</h6>
                    <p>{{ $payment->notes ?? 'No additional notes' }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <p class="text-muted">Thank you for your payment!</p>
                    <p class="text-muted small">This receipt was generated by Your Gym Name. For any inquiries, please contact us at info@yourgym.com.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
@media print {
    .card-header .btn,
    .card-header .btn-group {
        display: none !important;
    }
    .container-xxl {
        padding: 0 !important;
    }
    .card {
        border: none !important;
        box-shadow: none !important;
    }
}
</style>
@endsection